# Generated by Django 4.0 on 2022-01-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='participants',
            new_name='visitors_participants',
        ),
        migrations.RemoveField(
            model_name='band',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='bands_participants',
            field=models.ManyToManyField(blank=True, related_name='participated_in', to='concerts.Band'),
        ),
    ]
