# Generated by Django 4.0 on 2022-01-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('concerts', '0002_rename_participants_event_visitors_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bands_participants',
        ),
        migrations.AddField(
            model_name='band',
            name='participated_in',
            field=models.ManyToManyField(blank=True, to='concerts.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='visitors_participants',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
