# Generated by Django 4.0 on 2022-01-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_remove_event_bands_participants_band_participated_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='participated_in',
            field=models.ManyToManyField(blank=True, related_name='bands_participated', to='concerts.Event'),
        ),
    ]
