# Generated by Django 4.0 on 2022-01-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
        ('concerts', '0004_alter_band_participated_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='visitors_participants',
            field=models.ManyToManyField(blank=True, to='accounts.Profile'),
        ),
    ]
