# Generated by Django 4.0 on 2022-01-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0005_alter_event_visitors_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
