# Generated by Django 4.0 on 2022-01-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0008_alter_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, default='concerts/no_poster.jpg', upload_to='files/concerts/posters', verbose_name='Image'),
        ),
    ]
