# Generated by Django 4.0 on 2022-01-28 21:41

import concerts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0009_alter_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, default='concerts/no_poster.jpg', upload_to=concerts.models.upload_to, verbose_name='Image'),
        ),
    ]
